apiVersion: v1
kind: ConfigMap
metadata:
  name: git-mirror-known-hosts
  namespace: git-mirror-operator-system
data:
  known_hosts: |
    # Replace with keys from:
    #   ssh-keyscan github.com codeberg.org
    github.com ssh-ed25519 PLACEHOLDER
    codeberg.org ssh-ed25519 PLACEHOLDER
