apiVersion: v1
kind: Service
metadata:
  name: git-mirror-operator
  namespace: git-mirror-operator-system
  labels:
    app.kubernetes.io/name: git-mirror-operator
spec:
  selector:
    app.kubernetes.io/name: git-mirror-operator
  ports:
    - name: http
      port: 80
      targetPort: http
