# This rule is not used by the project git-mirror-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over mirror.shamubernetes.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: git-mirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: gitmirror-admin-role
rules:
- apiGroups:
  - mirror.shamubernetes.com
  resources:
  - gitmirrors
  verbs:
  - '*'
- apiGroups:
  - mirror.shamubernetes.com
  resources:
  - gitmirrors/status
  verbs:
  - get
