apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: git-mirror-operator
rules:
  - apiGroups: ["mirror.maude.dev"]
    resources: ["gitmirrors"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["mirror.maude.dev"]
    resources: ["gitmirrors/status"]
    verbs: ["get", "update", "patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: git-mirror-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: git-mirror-operator
subjects:
  - kind: ServiceAccount
    name: git-mirror-operator
    namespace: git-mirror-operator-system
