apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-mirror-operator
  namespace: git-mirror-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: git-mirror-sync
  namespace: git-mirror-operator-system
