apiVersion: v1
kind: Secret
metadata:
  name: source-repo-github-webhook
type: Opaque
stringData:
  secret: replace-with-github-webhook-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-source-ssh
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-with-source-repository-deploy-key
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-target-ssh
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-with-target-repository-deploy-key
    -----END OPENSSH PRIVATE KEY-----
