apiVersion: v1
kind: Secret
metadata:
  name: source-repo-github-webhook
type: Opaque
stringData:
  secret: replace-with-github-webhook-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-source-ssh
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-with-source-repository-deploy-key
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-target-ssh
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-with-target-repository-deploy-key
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-target-basic
type: Opaque
stringData:
  username: replace-with-https-git-username
  password: replace-with-https-git-token-or-password
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-github-app
type: Opaque
stringData:
  app-id: replace-with-github-app-client-id-or-app-id
  installation-id: replace-with-github-app-installation-id
  private-key.pem: |
    -----BEGIN RSA PRIVATE KEY-----
    replace-with-github-app-private-key
    -----END RSA PRIVATE KEY-----
