apiVersion: v1
kind: Secret
metadata:
  name: source-repo-github-webhook
  namespace: git-mirror-operator-system
type: Opaque
stringData:
  secret: replace-me
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-source-ssh
  namespace: git-mirror-operator-system
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-me
    -----END OPENSSH PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: source-repo-target-ssh
  namespace: git-mirror-operator-system
type: kubernetes.io/ssh-auth
stringData:
  ssh-privatekey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    replace-me
    -----END OPENSSH PRIVATE KEY-----
